### ISSUE TITLE
Add support for 10/12 bit inputs

### ISSUE THREAD

**Issue by ChristianFeldmann** [cd-athena/VCA#14]
There should not be too much fixing but some. So the idea is that we just always do an 8 bit DCT and just discard the higher bits. This should not really lower the precision when it comes to scene cut detection

**Comment by Ali-Flt** [comment]
Any updates on this? 
The worst part is that [the command line options](https://cd-athena.github.io/VCA/cli.html) states that vca reads input bit depth from y4m file or accepts it as input but in reality it ignores it entirely and produces wrong results for higher bit depths (or just returns segmentation fault). 
I converted a 8-bit y4m with 180 frames into yuv420p12le (12 bit) and when running VCA, it just detects twice the number of frames (359) assuming 8-bit and runs the algorithm on each 8 bit frame. 
Either update the documents stating it only supports 8-bit or add the support please.

**Comment by Ali-Flt** [comment]
I feel like I found the issue, it's probably in the Y4M sparse code
```
else if (parameterIndicator == 'C')
        {
            auto indicator = field.substr(1, 3);
            if (indicator == "420")
            {
                this->frameInfo.colorspace = vca_colorSpace::YUV420;
                vca_log(LogLevel::Info, "Y4M Detected colorspace 4:2:0");
            }
            else if (indicator == "422")
            {
                this->frameInfo.colorspace = vca_colorSpace::YUV422;
                vca_log(LogLevel::Info, "Y4M Detected colorspace 4:2:2");
            }
            else if (indicator == "444")
            {
                this->frameInfo.colorspace = vca_colorSpace::YUV444;
                vca_log(LogLevel::Info, "Y4M Detected colorspace 4:4:4");
            }
            else
                vca_log(LogLevel::Info,
                        "Y4M invalid colorspace indicator (" + indicator + "). Assuming 4:2:0.");
        }
```
I think you need to also read the bit depth in this if statement. Right now it's just defaulting to 8.

EDIT: Never mind I just saw this:
```
if (frame->info.bitDepth > 8)
        throw std::invalid_argument("16 bit input not implemented yet");
```

**Comment by ChristianFeldmann** [comment]
I just checked and adding the YUV bit depth parsing was quite easy. Now we just need a function to internally handle the values. The plan for now is to just truncate everything to 8 bits no matter what the input bit depth is.

**Comment by ChristianFeldmann** [comment]
Alright. I just added an update to the processing of 10 bit content. We are now chopping off bits so that we always analyze 8 bit values. Could you give it a test run? Its in the linked PR.

**Comment by Ali-Flt** [comment]
Is this a good approach to just ignore the upper 8 bits? Because for example if you convert an 8-bit video to 12-bit using this command:
```
ffmpeg  -y -i in_8.y4m -pix_fmt yuv420p12le -strict -1 out_12.y4m
```
ffmpeg does not just add 8 zero bits to each YUV value, instead it scales each value by 16 (12 bit - 8 bit = 4 bit shift => 2^4 = 16) to cover the whole new range (0 - 4095)
so if for instance a Y value is 71 in the 8-bit input, it will be 1136 in the 12-bit output. 
So I assume the correct approach would be to either process in 16 bits or scale the values back to 8 bits range (0-255) before processing (which I think will slow VCA by a great factor).

I ran VCA on 8, 10, 12 and 16 bits videos (all converted from 8 bit using the above command) and the results vary a lot.
Tables show 8, 10, 12 and 16 bits result from left to right respectively.
![image](https://user-images.githubusercontent.com/60854595/195996659-2e5f9b56-78a0-4502-8f07-d7f511a517ac.png)

**Comment by ChristianFeldmann** [comment]
Hi Ali.
Thanks for testing this. I did not get around testing this more in depth. Maybe there is still some issue in the code. Thats also why I did not merge it yet. 
Sorry I did not phrase this well. So of course I am not chopping off the most significant bits but the least significant bits. So this should be a very primitive approach to the same to what ffmpeg does when you do the conversion. Essentially when going from 10 to 8 bit I am dividing all integers by 4.
Good idea about the test with multiple bit depts. I will do the same and see. In theory they should all result in the same measurement. Maybe with some slight rounding differences but nothing major.

**Comment by ChristianFeldmann** [comment]
Alright I have found some bugs with the scaling of higher bit depths back down to 8. I am now seeing identical values for 8 10 and 16 bits. The values are just a tiny bit different for the chroma components. But the values are already different a bit in the input. My guess is that ffmpeg does something smarter to chroma then just adding more bits to each values. 
Could you give it another try?

**Comment by Ali-Flt** [comment]
The results seem to be very close for different bit depths now.

![image](https://user-images.githubusercontent.com/60854595/196236890-1d539c07-217f-411e-bfb2-88642c47f234.png)

**Comment by vigneshvijay94** [comment]
Thanks, @Ali-Flt for your feedback. I think we can push this to the branch now. In the later stage, we shall try to consider avoiding scaling down to 8bpp by having a 16-bit buffer for pixels (a high bit-depth build). This should have some additional memory overhead, but shall be precise.

**Comment by ChristianFeldmann** [comment]
Yep we could do the transform also natively for high bit depts (10/12) bits. However, I don't think the code will work for 16 bit as currently implemented since 16 bit is also not supported by x265 where the transform code was taken from. I would also require a bit more engineering to see if how the energy estimation behaves in this case. Also its a big questionmark how this behaves. Ultimately we could probably have this as a setting if the native bit depth should be used or if we should scale it to 8 bits.
Awesome. But I think then we can close this for now.
