### ISSUE TITLE
YUView csv data issues

### ISSUE THREAD

**Issue by ChristianFeldmann** [cd-athena/VCA#55]
There are some issues with the yuview stats file:
 - brightnessPerBlock: The code for this looks completely wrong.
 - energyPerBlock: For this, the scaling of the heat map is too low. I think we don't scale these to the block size anymore. I think we should when outputting them to the file. Maybe we could even update the scale data after all the frames were written and track the maximum. (same for the others)

**Comment by vigneshvijay94** [comment]
v1.0 doesn't seem to have any problem. This issue is noticed in v1.5. The "BlockEnergy" field in YUView stats seems corrupted.
