### ISSUE TITLE
Speed reduction in v1.5

### ISSUE THREAD

**Issue by vigneshvijay94** [cd-athena/VCA#56]
The analysis speed of 2160p videos in v1.0 was 370fps using 8 CPU threads and enabling SIMD. But the speed has done down (to almost half) in v1.5.

**Comment by ChristianFeldmann** [comment]
I just tested the performance test tool with version 1.0 and the latest stable branch:
 - 1.0 (the AVX2 results are): 1054.85fps, 923.36fps, 1054.85fps
 - stable: 967.12fps, 1098.90fps, 903.34fps

So I would say that this is well within the margin of error here.
