### ISSUE TITLE
Build error in Debian Linux

### ISSUE THREAD

**Issue by JingwenZZHU** [cd-athena/VCA#62]
tried to build in this system:
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"

Error log:
/home/zhu/.linuxbrew/bin/ld: CMakeFiles/vca.dir/__/common/input/Y4MInput.cpp.o: in function `vca::Y4MInput::Y4MInput(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
Y4MInput.cpp:(.text+0x2386): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/home/zhu/.linuxbrew/bin/ld: Y4MInput.cpp:(.text+0x238e): undefined reference to `std::filesystem::file_size(std::filesystem::__cxx11::path const&)'
/home/zhu/.linuxbrew/bin/ld: CMakeFiles/vca.dir/__/common/input/YUVInput.cpp.o: in function `vca::YUVInput::YUVInput(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, vca_frame_info&)':
YUVInput.cpp:(.text+0x2fb): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/home/zhu/.linuxbrew/bin/ld: YUVInput.cpp:(.text+0x303): undefined reference to `std::filesystem::file_size(std::filesystem::__cxx11::path const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [source/apps/vca/CMakeFiles/vca.dir/build.make:160: source/apps/vca/vca] Error 1
make[1]: *** [CMakeFiles/Makefile2:146: source/apps/vca/CMakeFiles/vca.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
zhu@bigboss:~/VCA/build$

**Comment by vigneshvijay94** [comment]
This issue is fixed with the commit 2811b9f
