### ISSUE TITLE
Hello ,  I'm trying to use your API for my python code, but I don't understand how to access it exactly. 

### ISSUE THREAD

**Issue by brahimfarhat** [cd-athena/VCA#78]

**Comment by vigneshvijay94** [comment]
Hi, currently, we test only with C/C++ code. We have a CLI application in the source code, which uses the APIs implemented in the library. Adding API for python code is something we plan to do in the future.

**Comment by MyGodItsFull0fStars** [comment]
Hi @brahimfarhat, thank you for your submission! In the future, we are planning to provide VCA as a Python library. 

Could you provide us with your use case or a code snippet so we might find a solution with the current state of the project? 😀

**Comment by brahimfarhat** [comment]
Hi, Thank you for your answer. I will try to use through the CLI for the mean time. I hope in the future we can get API for python. 
Thanks!

**Comment by MyGodItsFull0fStars** [comment]
Hi, something you could also do inside of a Python script is to use it with the `os` library.

For example to execute VCA you could do something similar to `os.system('ffmpeg-i input_file.mp4 -f yuv4mpegpipe - | path/to/vca --y4m --input stdin')` inside of Python for now.

**Comment by MyGodItsFull0fStars** [comment]
I am closing this issue for now. Hope I could help you with the current solution.
